server:
  log_level: info

prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
    external_labels:
      cluster: production
      service: pre-processing-service

  configs:
    - name: pre-processing-service-metrics
      remote_write:
        - url: ${GRAFANA_CLOUD_PROMETHEUS_URL}
          basic_auth:
            username: ${GRAFANA_CLOUD_PROMETHEUS_USER}
            password: ${GRAFANA_CLOUD_API_KEY}

      scrape_configs:
        - job_name: 'pre-processing-service'
          static_configs:
            - targets: ['pre-processing-service:8000']
          metrics_path: '/actuator/prometheus'
          scrape_interval: 15s
          params:
            format: ['prometheus']

        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']
          scrape_interval: 15s