spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver

  hikari:
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 10
    minimum-idle: 5
    pool-name: HikariCP-MyBatis

    # Gmail 연동 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
#  quartz:
#    jdbc:
#      initialize-schema: never

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: site.icebang.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: file:config/log4j2-production.yml
