# src/test/resources/application-test.yml
spring:
  config:
    activate:
      on-profile: test-unit

  # H2 인메모리 데이터베이스 설정 (Unit Test용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MariaDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 웹 콘솔 활성화 (디버깅용)
  h2:
    console:
      enabled: true

  hikari:
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 10
    minimum-idle: 5
    pool-name: HikariCP-MyBatis

  # JPA 설정 (H2용)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # SQL 스크립트 초기화 설정
  sql:
    init:
      mode: embedded # H2 같은