spring:
  config:
    activate:
      on-profile: test-e2e

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema/00-drop-maria.sql
        - classpath:sql/schema/01-schema.sql
        - classpath:sql/schema/02-quartz-schema.sql
        - classpath:sql/schema/03-schema-mariadb-timezone.sql
      data-locations:
        - classpath:sql/data/00-truncate.sql
        - classpath:sql/data/01-insert-internal-users.sql
        - classpath:sql/data/02-insert-external-users.sql
        - classpath:sql/data/03-insert-workflow.sql
        - classpath:sql/data/05-fix-timezone-data.sql
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: site.icebang.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2-test-e2e.yml