# src/test/resources/application-test.yml
spring:
  config:
    activate:
      on-profile: test

  # PostgreSQL 데이터베이스 연결 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/pre_process
    username: postgres
    password: qwer1234
    driver-class-name: org.postgresql.Driver

  hikari:
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 10
    minimum-idle: 5
    pool-name: HikariCP-MyBatis

  # SQL 스크립트 초기화 설정 추가
  sql:
    init:
      mode: always # 내장 DB가 아니더라도 항상 스크립트를 실행하도록 설정

mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.gltkorea.icebang.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2-test.yml