version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pre_process
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: qwer1234
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  pre-processing-service:
    build:
      context: ../../apps/pre-processing-service        # 프로젝트 루트 (Dockerfile이 루트에 없으면 맞게 조정)
      dockerfile: Dockerfile     # Dockerfile 경로 (루트에 없다면 상대경로로 수정)
    image: pre-processing-service:latest
    container_name: pre-processing-service
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../../apps/pre-processing-service/.env # 공통
      - ../../apps/pre-processing-service/dev.env    # 개발

volumes:
  postgres_data:
  pgadmin_data: