version: '3.8'

services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_DATABASE: pre_process
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: qwer1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mariadb", "-pqwer1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: qwer1234
    ports:
      - "8888:80"
    depends_on:
      - mariadb

#  pre-processing-service:
#    build:
#      context: ../../apps/pre-processing-service        # 프로젝트 루트 (Dockerfile이 루트에 없으면 맞게 조정)
#      dockerfile: Dockerfile     # Dockerfile 경로 (루트에 없다면 상대경로로 수정)
#    image: pre-processing-service:latest
#    container_name: pre-processing-service
#    restart: always
#    ports:
#      - "8000:8000"
#    env_file:
#      - ../../apps/pre-processing-service/.env # 공통
#      - ../../apps/pre-processing-service/dev.env    # 개발

volumes:
  mariadb_data: