server:
  log_level: info

prometheus:
  wal_directory: /tmp/grafana-agent-wal
  global:
    scrape_interval: 15s
    external_labels:
      cluster: production
      service: user-service

  configs:
    - name: user-service-metrics
      remote_write:
        - url: ${GRAFANA_CLOUD_PROMETHEUS_URL}
          basic_auth:
            username: ${GRAFANA_CLOUD_PROMETHEUS_USER}
            password: ${GRAFANA_CLOUD_API_KEY}

      scrape_configs:
        - job_name: 'user-service'
          static_configs:
            - targets: ['user-service:8081']  # 컨테이너 간 통신은 가능
          metrics_path: '/actuator/prometheus'
          scrape_interval: 15s
          params:
            format: ['prometheus']