version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network

  user-service:
    image: ghcr.io/kernel180-be12/final-4team-icebang/user-service:latest
    container_name: user-service
    restart: on-failure:3
    depends_on:
      - promtail
    ports:
      - "8080:8080"
      - "127.0.0.1:8081:8081"  # actuator만 localhost 접근
    networks:
      - app-network
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - logs_volume:/logs
      - ./config:/app/config:ro

  # Grafana Agent만으로 메트릭 수집 + 전송
  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    restart: unless-stopped
    volumes:
      - ./agent-config.yml:/etc/agent/agent.yml:ro
    networks:
      - app-network
    env_file:
      - .env.prod
    command:
      - --config.file=/etc/agent/agent.yml
      - --config.expand-env=true

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - logs_volume:/logs
    command:
      - -config.file=/etc/promtail/config.yml
      - -config.expand-env=true
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    env_file:
      - .env.prod
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "127.0.0.1:9100:9100"  # localhost에서만 접근
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  logs_volume:
    driver: local

networks:
  app-network:
    driver: bridge