openapi: 3.0.1
info:
  title: IceBang API
  description: IceBang API Documentation
  version: 0.0.1-alpha-snapshot
servers:
- url: http://localhost:8080
tags: []
paths:
  /v0/organizations:
    get:
      tags:
      - Organization
      summary: 조직 목록 조회
      description: 시스템에 등록된 모든 조직의 목록을 조회합니다
      operationId: organizations-list
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v0-organizations147125821"
              examples:
                organizations-list:
                  value: |-
                    {
                      "success" : true,
                      "data" : [ {
                        "id" : 3,
                        "organizationName" : "icebang"
                      }, {
                        "id" : 5,
                        "organizationName" : "디지털솔루션"
                      }, {
                        "id" : 6,
                        "organizationName" : "크리에이티브웍스"
                      }, {
                        "id" : 4,
                        "organizationName" : "테크이노베이션"
                      } ],
                      "message" : "OK",
                      "status" : "OK"
                    }
  /v0/auth/login:
    post:
      tags:
      - Authentication
      summary: 사용자 로그인
      description: 이메일과 비밀번호로 사용자 인증을 수행합니다
      operationId: auth-login
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/v0-auth-login1104623872"
            examples:
              auth-login:
                value: |-
                  {
                    "password" : "qwer1234!A",
                    "email" : "admin@icebang.site"
                  }
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v0-auth-logout-534880983"
              examples:
                auth-login:
                  value: |-
                    {
                      "success" : true,
                      "data" : null,
                      "message" : "OK",
                      "status" : "OK"
                    }
  /v0/auth/logout:
    post:
      tags:
      - Authentication
      summary: 사용자 로그아웃
      description: 현재 인증된 사용자의 세션을 무효화합니다
      operationId: auth-logout
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v0-auth-logout-534880983"
              examples:
                auth-logout:
                  value: |-
                    {
                      "success" : true,
                      "data" : null,
                      "message" : "OK",
                      "status" : "OK"
                    }
  /v0/workflow-runs/{runId}:
    get:
      tags:
      - Workflow History
      summary: 워크플로우 실행 상세 조회
      description: 워크플로우 실행 ID로 상세 정보를 조회합니다
      operationId: workflow-run-detail
      parameters:
      - name: runId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v0-workflow-runs-runId-1344315588"
              examples:
                workflow-run-detail:
                  value: |-
                    {
                      "success" : true,
                      "data" : {
                        "traceId" : "3e3c832d-b51f-48ea-95f9-98f0ae6d3413",
                        "workflowRun" : {
                          "id" : 1,
                          "workflowId" : 1,
                          "workflowName" : "상품 분석 및 블로그 자동 발행",
                          "workflowDescription" : "키워드 검색부터 상품 분석 후 블로그 발행까지의 자동화 프로세스",
                          "runNumber" : null,
                          "status" : "FAILED",
                          "triggerType" : null,
                          "startedAt" : "2025-09-22 18:18:43",
                          "finishedAt" : "2025-09-22 18:18:44",
                          "durationMs" : 1000,
                          "createdBy" : null,
                          "createdAt" : "2025-09-22 12:46:06.777248"
                        },
                        "jobRuns" : [ {
                          "id" : 1,
                          "workflowRunId" : 1,
                          "jobId" : 1,
                          "jobName" : "상품 분석",
                          "jobDescription" : "키워드 검색, 상품 크롤링 및 유사도 분석 작업",
                          "status" : "FAILED",
                          "executionOrder" : null,
                          "startedAt" : "2025-09-22 18:18:44",
                          "finishedAt" : "2025-09-22 18:18:44",
                          "durationMs" : 0,
                          "taskRuns" : [ {
                            "id" : 1,
                            "jobRunId" : 1,
                            "taskId" : 1,
                            "taskName" : "키워드 검색 태스크",
                            "taskDescription" : null,
                            "taskType" : "FastAPI",
                            "status" : "FAILED",
                            "executionOrder" : null,
                            "startedAt" : "2025-09-22 18:18:44",
                            "finishedAt" : "2025-09-22 18:18:44",
                            "durationMs" : 0
                          } ]
                        } ]
                      },
                      "message" : "OK",
                      "status" : "OK"
                    }
  /v0/organizations/{organizationId}/options:
    get:
      tags:
      - Organization
      summary: 조직 옵션 정보 조회
      description: "특정 조직의 부서, 직급, 역할 옵션 정보를 조회합니다"
      operationId: organizations-options
      parameters:
      - name: organizationId
        in: path
        description: 조직 ID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/v0-organizations-organizationId-options-50182786"
              examples:
                organizations-options:
                  value: |-
                    {
                      "success" : true,
                      "data" : {
                        "departments" : [ {
                          "id" : 31,
                          "name" : "AI개발팀"
                        }, {
                          "id" : 36,
                          "name" : "기획팀"
                        }, {
                          "id" : 32,
                          "name" : "데이터팀"
                        }, {
                          "id" : 34,
                          "name" : "마케팅팀"
                        }, {
                          "id" : 35,
                          "name" : "운영팀"
                        }, {
                          "id" : 33,
                          "name" : "콘텐츠팀"
                        } ],
                        "positions" : [ {
                          "id" : 36,
                          "title" : "CEO"
                        }, {
                          "id" : 37,
                          "title" : "CTO"
                        }, {
                          "id" : 39,
                          "title" : "시니어"
                        }, {
                          "id" : 41,
                          "title" : "인턴"
                        }, {
                          "id" : 40,
                          "title" : "주니어"
                        }, {
                          "id" : 38,
                          "title" : "팀장"
                        } ],
                        "roles" : [ {
                          "id" : 60,
                          "name" : "AI_ENGINEER",
                          "description" : "AI 엔지니어 - AI 모델 개발 및 최적화"
                        }, {
                          "id" : 63,
                          "name" : "CONTENT_CREATOR",
                          "description" : "콘텐츠 크리에이터 - 바이럴 콘텐츠 제작"
                        }, {
                          "id" : 64,
                          "name" : "CONTENT_MANAGER",
                          "description" : "콘텐츠 매니저 - 콘텐츠 기획 및 관리"
                        }, {
                          "id" : 62,
                          "name" : "CRAWLING_ENGINEER",
                          "description" : "크롤링 엔지니어 - 웹 크롤링 시스템 개발"
                        }, {
                          "id" : 61,
                          "name" : "DATA_SCIENTIST",
                          "description" : "데이터 사이언티스트 - 데이터 분석 및 인사이트 도출"
                        }, {
                          "id" : 66,
                          "name" : "MARKETING_ANALYST",
                          "description" : "마케팅 분석가 - 마케팅 성과 분석"
                        }, {
                          "id" : 67,
                          "name" : "OPERATIONS_MANAGER",
                          "description" : "운영 매니저 - 시스템 운영 및 모니터링"
                        }, {
                          "id" : 65,
                          "name" : "WORKFLOW_ADMIN",
                          "description" : "워크플로우 관리자 - 자동화 프로세스 관리"
                        } ]
                      },
                      "message" : "OK",
                      "status" : "OK"
                    }
components:
  schemas:
    v0-workflow-runs-runId-1344315588:
      type: object
      properties:
        data:
          type: object
          properties:
            traceId:
              type: string
              description: 워크플로우 실행 추적 ID
            workflowRun:
              type: object
              properties:
                createdAt:
                  type: string
                  description: 생성 시간
                startedAt:
                  type: string
                  description: 시작 시간
                workflowName:
                  type: string
                  description: 워크플로우 이름
                id:
                  type: number
                  description: 워크플로우 실행 ID
                workflowDescription:
                  type: string
                  description: 워크플로우 설명
                durationMs:
                  type: number
                  description: 실행 시간(ms)
                workflowId:
                  type: number
                  description: 워크플로우 설계 ID
                finishedAt:
                  type: string
                  description: 완료 시간
                status:
                  type: string
                  description: 실행 상태
              description: 워크플로우 실행 정보
            jobRuns:
              type: array
              description: Job 실행 목록
              items:
                type: object
                properties:
                  jobName:
                    type: string
                    description: Job 이름
                  taskRuns:
                    type: array
                    description: Task 실행 목록
                    items:
                      type: object
                      properties:
                        taskType:
                          type: string
                          description: Task 유형
                        startedAt:
                          type: string
                          description: Task 시작 시간
                        taskName:
                          type: string
                          description: Task 이름
                        id:
                          type: number
                          description: Task 실행 ID
                        jobRunId:
                          type: number
                          description: Job 실행 ID
                        durationMs:
                          type: number
                          description: Task 실행 시간(ms)
                        taskId:
                          type: number
                          description: Task 설계 ID
                        finishedAt:
                          type: string
                          description: Task 완료 시간
                        status:
                          type: string
                          description: Task 실행 상태
                  jobId:
                    type: number
                    description: Job 설계 ID
                  startedAt:
                    type: string
                    description: Job 시작 시간
                  jobDescription:
                    type: string
                    description: Job 설명
                  id:
                    type: number
                    description: Job 실행 ID
                  durationMs:
                    type: number
                    description: Job 실행 시간(ms)
                  workflowRunId:
                    type: number
                    description: 워크플로우 실행 ID
                  finishedAt:
                    type: string
                    description: Job 완료 시간
                  status:
                    type: string
                    description: Job 실행 상태
          description: 응답 데이터
        success:
          type: boolean
          description: 요청 성공 여부
        message:
          type: string
          description: 응답 메시지
        status:
          type: string
          description: HTTP 상태
    v0-auth-logout-534880983:
      type: object
      properties:
        success:
          type: boolean
          description: 요청 성공 여부
        message:
          type: string
          description: 응답 메시지
        status:
          type: string
          description: HTTP 상태
    v0-auth-login1104623872:
      type: object
      properties:
        password:
          type: string
          description: 사용자 비밀번호
        email:
          type: string
          description: 사용자 이메일 주소
    v0-organizations147125821:
      type: object
      properties:
        data:
          type: array
          description: 조직 목록
          items:
            type: object
            properties:
              organizationName:
                type: string
                description: 조직명
              id:
                type: number
                description: 조직 ID
        success:
          type: boolean
          description: 요청 성공 여부
        message:
          type: string
          description: 응답 메시지
        status:
          type: string
          description: HTTP 상태
    v0-organizations-organizationId-options-50182786:
      type: object
      properties:
        data:
          type: object
          properties:
            roles:
              type: array
              description: 역할 목록
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: 역할명
                  description:
                    type: string
                    description: 역할 설명
                  id:
                    type: number
                    description: 역할 ID
            positions:
              type: array
              description: 직급 목록
              items:
                type: object
                properties:
                  id:
                    type: number
                    description: 직급 ID
                  title:
                    type: string
                    description: 직급명
            departments:
              type: array
              description: 부서 목록
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: 부서명
                  id:
                    type: number
                    description: 부서 ID
          description: 옵션 데이터
        success:
          type: boolean
          description: 요청 성공 여부
        message:
          type: string
          description: 응답 메시지
        status:
          type: string
          description: HTTP 상태
