[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "pre-processing-service"
version = "0.1.0"
description = ""
authors = [
    {name = "skip"}
]

requires-python = ">=3.11,<4.0"
dependencies = [
    # FastAPI: 비동기 웹 프레임워크, REST API 서버 구현에 사용
    "fastapi (>=0.116.1,<0.117.0)",
    # Uvicorn: ASGI 서버, FastAPI 앱 실행에 필요
    "uvicorn (>=0.35.0,<0.36.0)",
    # Loguru: 간편하고 강력한 로깅 라이브러리, 로그 관리에 사용
    "loguru (>=0.7.3,<0.8.0)",
    # pytest: 테스트 프레임워크, 단위 테스트 및 통합 테스트에 사용
    "pytest (>=8.4.1,<9.0.0)"
]

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^1.1.0"

[tool.poetry.group.test.dependencies]
pytest-asyncio = "^1.1.0"

[tool.poetry]
packages = [{include = "app"}]