name: Release Drafter

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Pre-processing service
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-pre-processing.yml
          name: 'pre-processing-v$RESOLVED_VERSION'
          tag: 'pre-processing-v$RESOLVED_VERSION'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # User service
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-user-service.yml
          name: 'user-service-v$RESOLVED_VERSION'
          tag: 'user-service-v$RESOLVED_VERSION'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}